# Generated by Django 3.2.4 on 2021-06-20 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('idReseña', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de la reseña')),
                ('numeroEstrellas', models.CharField(max_length=1, verbose_name='Numero estrellas')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('nombreUsuario', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Nombre Completo')),
                ('edad', models.CharField(max_length=1, verbose_name='Edad')),
                ('correoElectronico', models.CharField(max_length=40, verbose_name='Correo Electrónico')),
                ('personalContratado', models.CharField(max_length=40, verbose_name='Nombre del Personal')),
                ('comentario', models.CharField(max_length=200, verbose_name='Comentario')),
                ('numeroEstrellas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
            ],
        ),
    ]
