# Generated by Django 3.2.4 on 2021-06-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_input_reseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='descrip',
            field=models.TextField(default='', max_length=150, verbose_name='Descripción especialidad'),
        ),
        migrations.AddField(
            model_name='personas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='input',
            name='comentario',
            field=models.TextField(max_length=200, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='input',
            name='numeroEstrellas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reseña'),
        ),
    ]
