# Generated by Django 3.2.4 on 2021-06-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210621_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='edad',
            field=models.CharField(max_length=2, verbose_name='Edad'),
        ),
    ]
